- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install dependencies
      command: yarn
      args:
        chdir: ../
    - name: Build the project
      command: yarn run build
      args:
        chdir: ../
    - name: Fetching coaster repository
      git:
        repo: https://github.com/TimFinucane/rp-companion.git
        dest: ./tmp/rp-companion/
    - name: Installing dependencies
      command: yarn
      args:
        chdir: ./tmp/rp-companion/client/
    - name: Compiling coaster repository
      shell: yarn build --env.URL_ROOT=/coaster
      args:
        chdir: ./tmp/rp-companion/client/

- hosts: webservers
  vars:
    http_port: 80
  remote_user: ec2-user
  tasks:
    - name: Ensure we have nginx installed
      yum: name=nginx state=latest

    - name: Install web files
      become: yes
      copy:
        src: ../dist/
        dest: /usr/share/nginx/html/
    - file:
        path: /usr/share/nginx/html/coaster/
        state: directory
      become: yes
    - copy:
        src: ./tmp/rp-companion/client/dist/
        dest: /usr/share/nginx/html/coaster/
      become: yes
